# We use a custom configuration
# language: haskell

# I do not wish to receive email notifications
notifications:
  email: false

# The following enables several GHC versions to be tested.
env:
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.18 GHCVER=7.8.3
 - CABALVER=1.22 GHCVER=7.10.1

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies -fbuildExamples --enable-tests --force-reinstalls

before_script:
  - cabal configure -fbuildExamples
  - cabal sdist
  - cd ..
  - tar -xf threepenny-gui/dist/threepenny-gui*.tar.gz
  - cd threepenny-gui*

script:
  - cabal configure -fbuildExamples --enable-tests && cabal build && cabal test
